### PR TITLE
Code Formatting: run astyle and add script

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by SkyzohKey** [comment]
The .vapi you edited wasn't up-to-date, I'll push the latest version of the vapi, could you remake this PR with the new toxcore.vapi ? :)

**Comment by SkyzohKey** [comment]
- Can you explain me what is the `astylerc` file ? ^^

**Comment by benwaffle** [comment]
Its a config file for http://astyle.sourceforge.net/ which can format your code

**Comment by SkyzohKey** [comment]
Ah! Nice :o, I'll push the current libtoxcore.vapi i have on my computer ^^'

**Pull request merged**
